export const initialChats = [
  { id: 1, title: "Labor Law Question", folderId: null },
  { id: 2, title: "Contract Issue", folderId: null }
];

export const initialFolders = [
  { id: 1, name: "Work", chatIds: [], color: "#BE2A41" },
  { id: 2, name: "Study", chatIds: [], color: "#E78A48" }
];

// id-kenttä on joko:
// - "cat:KategorianNimi" → backend hakee type=="law" + category==KategorianNimi
// - "tes:ParentArvo"    → backend hakee type=="tes_chunk" + parent==ParentArvo
export const lawsList = [
  {
    id: "cat:Työsuhde",
    firestoreType: "law",
    firestoreField: "category",
    firestoreValue: "Työsuhde",
    name: "Työsuhdelait",
    name_en: "Employment Laws",
    name_fi: "Työsuhdelait",
    category: "Työsuhde",
    category_en: "Employment",
    category_fi: "Työsuhde",
    link: "https://www.finlex.fi",
  },
  {
    id: "cat:Työaika ja vapaat",
    firestoreType: "law",
    firestoreField: "category",
    firestoreValue: "Työaika ja vapaat",
    name: "Työaika ja vapaat",
    name_en: "Working Hours & Leave",
    name_fi: "Työaika ja vapaat",
    category: "Työaika ja vapaat",
    category_en: "Working Hours & Leave",
    category_fi: "Työaika ja vapaat",
    link: "https://www.finlex.fi",
  },
  {
    id: "cat:Turvallisuus ja tasa-arvo",
    firestoreType: "law",
    firestoreField: "category",
    firestoreValue: "Turvallisuus ja tasa-arvo",
    name: "Turvallisuus ja tasa-arvo",
    name_en: "Safety & Equality",
    name_fi: "Turvallisuus ja tasa-arvo",
    category: "Turvallisuus ja tasa-arvo",
    category_en: "Safety & Equality",
    category_fi: "Turvallisuus ja tasa-arvo",
    link: "https://www.finlex.fi",
  },
  {
    id: "cat:Yhteistoiminta",
    firestoreType: "law",
    firestoreField: "category",
    firestoreValue: "Yhteistoiminta",
    name: "Yhteistoiminta",
    name_en: "Cooperation",
    name_fi: "Yhteistoiminta",
    category: "Yhteistoiminta",
    category_en: "Cooperation",
    category_fi: "Yhteistoiminta",
    link: "https://www.finlex.fi",
  },
  {
    id: "cat:Sote-lainsäädäntö",
    firestoreType: "law",
    firestoreField: "category",
    firestoreValue: "Sote-lainsäädäntö",
    name: "Sote-lainsäädäntö",
    name_en: "Social & Health Care Legislation",
    name_fi: "Sote-lainsäädäntö",
    category: "Sote-lainsäädäntö",
    category_en: "Social & Health Care Legislation",
    category_fi: "Sote-lainsäädäntö",
    link: "https://www.finlex.fi",
  },
  {
    id: "cat:Sosiaalipalvelut",
    firestoreType: "law",
    firestoreField: "category",
    firestoreValue: "Sosiaalipalvelut",
    name: "Sosiaalipalvelut",
    name_en: "Social Services",
    name_fi: "Sosiaalipalvelut",
    category: "Sosiaalipalvelut",
    category_en: "Social Services",
    category_fi: "Sosiaalipalvelut",
    link: "https://www.finlex.fi",
  },
  {
    id: "cat:Terveyspalvelut",
    firestoreType: "law",
    firestoreField: "category",
    firestoreValue: "Terveyspalvelut",
    name: "Terveyspalvelut",
    name_en: "Health Services",
    name_fi: "Terveyspalvelut",
    category: "Terveyspalvelut",
    category_en: "Health Services",
    category_fi: "Terveyspalvelut",
    link: "https://www.finlex.fi",
  },
  {
    id: "tes:HYVTES",
    firestoreType: "tes_chunk",
    firestoreField: "parent",
    firestoreValue: "HYVTES",
    name: "HYVTES",
    name_en: "Municipal Health and Social Services Agreement (HYVTES)",
    name_fi: "Hyvinvointialan yleinen virka- ja työehtosopimus (HYVTES)",
    category: "Työehtosopimukset",
    category_en: "Collective Agreements",
    category_fi: "Työehtosopimukset",
    link: "https://www.kt.fi/sopimukset/hyvtes/2025-2028/kokoteksti",
  },
  {
    id: "tes:SOTE-sopimus",
    firestoreType: "tes_chunk",
    firestoreField: "parent",
    firestoreValue: "SOTE-sopimus",
    name: "SOTE-sopimus",
    name_en: "Social and Health Care Collective Agreement (SOTE-sopimus)",
    name_fi: "Sosiaali- ja terveydenhuollon työehtosopimus (SOTE-sopimus)",
    category: "Työehtosopimukset",
    category_en: "Collective Agreements",
    category_fi: "Työehtosopimukset",
    link: "https://www.kt.fi/sopimukset/sote/2025-2028/kokoteksti",
  },
  {
    id: "tes:YTES",
    firestoreType: "tes_chunk",
    firestoreField: "parent",
    firestoreValue: "YTES",
    name: "YTES",
    name_en: "General Municipal Collective Agreement (YTES)",
    name_fi: "Kunnallinen yleinen virka- ja työehtosopimus (YTES)",
    category: "Työehtosopimukset",
    category_en: "Collective Agreements",
    category_fi: "Työehtosopimukset",
    link: "https://www.kt.fi/sopimukset/ytes/2025-2028/kokoteksti",
  },
];

export const initialMessages = [
  {
    role: "assistant",
    content: "WELCOME_VIEW",
  },
];